# -*- coding: utf-8 -*-
"""beeranalysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hBbXH_tE9QrynW6uTsMMh4kA4MCepdPj
"""

import pandas as pd
df = pd.read_csv('jsonformatter.csv')

df.head()

beer_dim = df[['name', 'tagline','description']].reset_index(drop=True)
beer_dim['beer_id']=beer_dim.index
beer_dim = beer_dim[['beer_id','name', 'tagline','description']]
beer_dim.head()



date_brewed_dim = df[['first_brewed']].reset_index(drop=True)
date_brewed_dim['date_id'] = date_brewed_dim.index
date_brewed_dim=date_brewed_dim[['date_id','first_brewed']]
date_brewed_dim.head()

image_dim = df[['image_url']].reset_index(drop=True)
image_dim['image_id']=image_dim.index
image_dim=image_dim[['image_id','image_url']]
image_dim.head()

ingredients_dim = df[['ingredients']].reset_index(drop=True)
ingredients_dim['ingredients_id'] = ingredients_dim.index
ingredients_dim= ingredients_dim[['ingredients_id','ingredients']]
ingredients_dim.head()

food_pairing_dim = df[['food_pairing']].reset_index(drop=True)
food_pairing_dim['food_pairing_id'] = food_pairing_dim.index
food_pairing_dim = food_pairing_dim[['food_pairing_id','food_pairing']]
food_pairing_dim.head()

brewer_tips_dim = df[['brewers_tips']]
brewer_tips_dim['brewer_tips_id']=brewer_tips_dim.index
brewer_tips_dim = brewer_tips_dim[['brewer_tips_id', 'brewers_tips']]
brewer_tips_dim.head()

fact_table = df.merge(beer_dim, on=['name', 'tagline','description']) \
              .merge(date_brewed_dim, on='first_brewed') \
              .merge(image_dim, on='image_url') \
              .merge(ingredients_dim, on='ingredients') \
              .merge(food_pairing_dim, on='food_pairing') \
              .merge(brewer_tips_dim, on='brewers_tips') \
              [['id', 'beer_id','abv','ibu','target_fg','target_og','ebc','srm','ph','attenuation_level', 'date_id', 'image_id', 'ingredients_id','food_pairing_id', 'brewer_tips_id']]

fact_table.head()

fact_table.drop_duplicates()

fact_table.info()